export interface SkillDefinition {
    id: string;
    name: string;
    variants: string[];
    category: 'hard' | 'soft' | 'tool' | 'certification';
}

export const SKILL_DATABASE: SkillDefinition[] = [

    // ─── PROGRAMMING LANGUAGES ───────────────────────────────────────────────
    { id: 'python', name: 'Python', variants: ['Python 3', 'Python 2', 'py'], category: 'hard' },
    { id: 'javascript', name: 'JavaScript', variants: ['JS', 'ES6', 'ES2015', 'ES2020', 'ECMAScript', 'Vanilla JS', 'Vanilla JavaScript'], category: 'hard' },
    { id: 'typescript', name: 'TypeScript', variants: ['TS', 'TSX'], category: 'hard' },
    { id: 'java', name: 'Java', variants: ['Java 8', 'Java 11', 'Java 17', 'Java EE', 'Jakarta EE'], category: 'hard' },
    { id: 'golang', name: 'Go', variants: ['Golang', 'Go Lang'], category: 'hard' },
    { id: 'rust', name: 'Rust', variants: ['Rust Lang', 'Rustlang'], category: 'hard' },
    { id: 'cpp', name: 'C++', variants: ['Cpp', 'C/C++', 'CPP'], category: 'hard' },
    { id: 'csharp', name: 'C#', variants: ['CSharp', 'C Sharp', 'dotnet c#', '.NET C#'], category: 'hard' },
    { id: 'ruby', name: 'Ruby', variants: ['rb', 'Ruby on Rails', 'RoR'], category: 'hard' },
    { id: 'php', name: 'PHP', variants: ['PHP 7', 'PHP 8', 'PHP/MySQL'], category: 'hard' },
    { id: 'swift', name: 'Swift', variants: ['SwiftUI', 'Swift 5'], category: 'hard' },
    { id: 'kotlin', name: 'Kotlin', variants: ['Kotlin Multiplatform', 'KMM'], category: 'hard' },
    { id: 'scala', name: 'Scala', variants: ['Scala 2', 'Scala 3'], category: 'hard' },
    { id: 'r_lang', name: 'R', variants: ['R Programming', 'R Language', 'R Studio', 'RStudio'], category: 'hard' },
    { id: 'matlab', name: 'MATLAB', variants: ['Matlab', 'MathWorks'], category: 'hard' },
    { id: 'c_lang', name: 'C', variants: ['C Language', 'C Programming'], category: 'hard' },
    { id: 'elixir', name: 'Elixir', variants: ['Elixir Lang', 'Phoenix Framework'], category: 'hard' },
    { id: 'dart', name: 'Dart', variants: ['Dart Lang'], category: 'hard' },
    { id: 'bash', name: 'Bash', variants: ['Shell Scripting', 'Bash Scripting', 'Shell Script', 'Zsh', 'Sh'], category: 'hard' },
    { id: 'powershell', name: 'PowerShell', variants: ['PS1', 'Windows PowerShell'], category: 'hard' },
    { id: 'html', name: 'HTML', variants: ['HTML5', 'HTML/CSS', 'HyperText Markup Language'], category: 'hard' },
    { id: 'css', name: 'CSS', variants: ['CSS3', 'Cascading Style Sheets', 'CSS Grid', 'Flexbox'], category: 'hard' },
    { id: 'sql', name: 'SQL', variants: ['Structured Query Language', 'SQL Queries', 'T-SQL', 'PL/SQL', 'SQL Server', 'SSMS', 'SSRS', 'MySQL', 'PostgreSQL', 'Oracle DB', 'NoSQL', 'MongoDB'], category: 'hard' },

    // ─── FRONTEND FRAMEWORKS & LIBRARIES ─────────────────────────────────────
    { id: 'react', name: 'React', variants: ['ReactJS', 'React.js', 'React Native', 'React Hooks', 'React Router', 'ReactJS Developer'], category: 'hard' },
    { id: 'nextjs', name: 'Next.js', variants: ['NextJS', 'Next JS', 'Nextjs'], category: 'hard' },
    { id: 'vuejs', name: 'Vue.js', variants: ['VueJS', 'Vue', 'Vue 3', 'Vuex', 'Nuxt', 'Nuxt.js'], category: 'hard' },
    { id: 'angular', name: 'Angular', variants: ['AngularJS', 'Angular 2+', 'Angular 12', 'Angular 14', 'Angular Material'], category: 'hard' },
    { id: 'svelte', name: 'Svelte', variants: ['SvelteKit'], category: 'hard' },
    { id: 'redux', name: 'Redux', variants: ['Redux Toolkit', 'Redux Saga', 'Redux Thunk', 'RTK'], category: 'hard' },
    { id: 'graphql', name: 'GraphQL', variants: ['Apollo GraphQL', 'Apollo Client', 'Apollo Server'], category: 'hard' },
    { id: 'tailwind', name: 'Tailwind CSS', variants: ['Tailwind', 'TailwindCSS'], category: 'tool' },
    { id: 'bootstrap', name: 'Bootstrap', variants: ['Bootstrap 5', 'Bootstrap 4'], category: 'tool' },
    { id: 'sass', name: 'SASS', variants: ['SCSS', 'Sass', 'CSS Preprocessor'], category: 'tool' },
    { id: 'webpack', name: 'Webpack', variants: ['Webpack 5', 'Module Bundler'], category: 'tool' },
    { id: 'vite', name: 'Vite', variants: ['Vite.js'], category: 'tool' },
    { id: 'jest', name: 'Jest', variants: ['Jest Testing', 'React Testing Library'], category: 'tool' },
    { id: 'cypress', name: 'Cypress', variants: ['Cypress.io', 'E2E Testing'], category: 'tool' },
    { id: 'playwright', name: 'Playwright', variants: ['Playwright Testing'], category: 'tool' },
    { id: 'storybook', name: 'Storybook', variants: ['Storybook.js'], category: 'tool' },

    // ─── BACKEND FRAMEWORKS ───────────────────────────────────────────────────
    { id: 'nodejs', name: 'Node.js', variants: ['NodeJS', 'Node', 'Express', 'Express.js', 'ExpressJS'], category: 'hard' },
    { id: 'django', name: 'Django', variants: ['Django REST', 'DRF', 'Django REST Framework'], category: 'hard' },
    { id: 'flask', name: 'Flask', variants: ['Flask Python'], category: 'hard' },
    { id: 'fastapi', name: 'FastAPI', variants: ['Fast API'], category: 'hard' },
    { id: 'spring', name: 'Spring Boot', variants: ['Spring', 'Spring Framework', 'Spring MVC', 'Spring Cloud', 'Spring Security', 'SpringBoot'], category: 'hard' },
    { id: 'rails', name: 'Ruby on Rails', variants: ['Rails', 'Rails API'], category: 'hard' },
    { id: 'nestjs', name: 'NestJS', variants: ['Nest.js'], category: 'hard' },
    { id: 'laravel', name: 'Laravel', variants: ['Laravel PHP', 'Laravel Framework'], category: 'hard' },
    { id: 'dotnet', name: '.NET', variants: ['.NET Core', '.NET 6', '.NET 7', '.NET 8', 'ASP.NET', 'ASP.NET Core', 'C# .NET'], category: 'hard' },
    { id: 'rest_api', name: 'REST API', variants: ['RESTful API', 'API Design', 'API Development', 'API Integration', 'gRPC', 'REST', 'REST APIs', 'Web Services'], category: 'hard' },
    { id: 'microservices', name: 'Microservices', variants: ['Microservice Architecture', 'Service-Oriented Architecture', 'SOA', 'Event-Driven Architecture', 'Distributed Systems'], category: 'hard' },

    // ─── CLOUD PLATFORMS ──────────────────────────────────────────────────────
    { id: 'aws', name: 'AWS', variants: ['Amazon Web Services', 'Amazon AWS', 'EC2', 'S3', 'Lambda', 'RDS', 'CloudFormation', 'ECS', 'EKS', 'CloudWatch', 'SQS', 'SNS', 'API Gateway', 'DynamoDB', 'Elastic Beanstalk', 'Route 53', 'CloudFront', 'Glue', 'EMR', 'Kinesis', 'Redshift'], category: 'tool' },
    { id: 'azure', name: 'Azure', variants: ['Microsoft Azure', 'Azure DevOps', 'Azure Functions', 'Azure AKS', 'Azure Blob', 'Azure SQL', 'Azure Active Directory', 'Azure Pipelines', 'Azure Monitor', 'Azure Data Factory', 'ADF'], category: 'tool' },
    { id: 'gcp', name: 'GCP', variants: ['Google Cloud Platform', 'Google Cloud', 'BigQuery', 'Cloud Run', 'GKE', 'Cloud Storage', 'Pub/Sub', 'Cloud Functions', 'Vertex AI', 'Dataflow', 'Cloud Spanner'], category: 'tool' },
    { id: 'digitalocean', name: 'DigitalOcean', variants: ['DO', 'DigitalOcean Droplets'], category: 'tool' },
    { id: 'heroku', name: 'Heroku', variants: ['Heroku Deployment'], category: 'tool' },
    { id: 'vercel', name: 'Vercel', variants: ['Vercel Deployment'], category: 'tool' },
    { id: 'cloudflare', name: 'Cloudflare', variants: ['Cloudflare Workers', 'Cloudflare CDN'], category: 'tool' },

    // ─── DEVOPS & INFRASTRUCTURE ──────────────────────────────────────────────
    { id: 'docker', name: 'Docker', variants: ['Containerization', 'Docker Compose', 'Dockerfile', 'Docker Swarm', 'Container Orchestration'], category: 'tool' },
    { id: 'kubernetes', name: 'Kubernetes', variants: ['K8s', 'K8', 'Helm', 'kubectl', 'Pod', 'Kubernetes Cluster'], category: 'tool' },
    { id: 'terraform', name: 'Terraform', variants: ['Infrastructure as Code', 'IaC', 'HCL', 'Terraform Cloud'], category: 'tool' },
    { id: 'ansible', name: 'Ansible', variants: ['Ansible Playbooks', 'Configuration Management'], category: 'tool' },
    { id: 'jenkins', name: 'Jenkins', variants: ['Jenkins CI', 'Jenkins Pipeline'], category: 'tool' },
    { id: 'github_actions', name: 'GitHub Actions', variants: ['GHA', 'Github Actions', 'GitHub CI/CD'], category: 'tool' },
    { id: 'gitlab_ci', name: 'GitLab CI', variants: ['GitLab CI/CD', 'GitLab Pipelines'], category: 'tool' },
    { id: 'circleci', name: 'CircleCI', variants: ['Circle CI'], category: 'tool' },
    { id: 'prometheus', name: 'Prometheus', variants: ['Prometheus Monitoring', 'PromQL'], category: 'tool' },
    { id: 'grafana', name: 'Grafana', variants: ['Grafana Dashboards'], category: 'tool' },
    { id: 'elk_stack', name: 'ELK Stack', variants: ['Elasticsearch Logstash Kibana', 'Elastic Stack', 'Kibana', 'Logstash'], category: 'tool' },
    { id: 'nginx', name: 'Nginx', variants: ['Nginx Server', 'Nginx Proxy', 'NGINX', 'Apache'], category: 'tool' },
    { id: 'linux', name: 'Linux', variants: ['Ubuntu', 'CentOS', 'Debian', 'Red Hat', 'RHEL', 'Unix', 'POSIX', 'Amazon Linux'], category: 'tool' },
    { id: 'git', name: 'Git', variants: ['GitHub', 'GitLab', 'Bitbucket', 'Version Control', 'Source Control', 'Git Flow'], category: 'tool' },
    { id: 'cicd', name: 'CI/CD', variants: ['Continuous Integration', 'Continuous Deployment', 'Continuous Delivery', 'DevOps Pipeline', 'Build Pipeline', 'CICD'], category: 'hard' },
    { id: 'devops', name: 'DevOps', variants: ['Dev Ops', 'DevSecOps', 'Platform Engineering', 'SRE', 'Site Reliability Engineering'], category: 'hard' },

    // ─── DATABASES ────────────────────────────────────────────────────────────
    { id: 'postgresql', name: 'PostgreSQL', variants: ['Postgres', 'PgSQL', 'PostGres'], category: 'tool' },
    { id: 'mysql', name: 'MySQL', variants: ['MySQL Database', 'MariaDB'], category: 'tool' },
    { id: 'mongodb', name: 'MongoDB', variants: ['Mongo', 'MongoDB Atlas', 'Document Database'], category: 'tool' },
    { id: 'redis', name: 'Redis', variants: ['Redis Cache', 'Redis Cluster', 'In-memory Cache', 'Caching'], category: 'tool' },
    { id: 'elasticsearch', name: 'Elasticsearch', variants: ['Elastic Search', 'Opensearch', 'Full-Text Search'], category: 'tool' },
    { id: 'cassandra', name: 'Cassandra', variants: ['Apache Cassandra', 'Cassandra DB'], category: 'tool' },
    { id: 'dynamodb', name: 'DynamoDB', variants: ['AWS DynamoDB'], category: 'tool' },
    { id: 'snowflake', name: 'Snowflake', variants: ['Snowflake DB', 'Snowflake Data Warehouse'], category: 'tool' },
    { id: 'bigquery', name: 'BigQuery', variants: ['Google BigQuery', 'GBQ'], category: 'tool' },
    { id: 'redshift', name: 'Redshift', variants: ['AWS Redshift', 'Amazon Redshift'], category: 'tool' },
    { id: 'databricks', name: 'Databricks', variants: ['Databricks Platform', 'Delta Lake', 'Lakehouse'], category: 'tool' },
    { id: 'neo4j', name: 'Neo4j', variants: ['Graph Database', 'Cypher'], category: 'tool' },
    { id: 'sqlite', name: 'SQLite', variants: ['SQLite3'], category: 'tool' },
    { id: 'oracle_db', name: 'Oracle Database', variants: ['Oracle DB', 'Oracle SQL', 'Oracle 19c'], category: 'tool' },
    { id: 'firebase', name: 'Firebase', variants: ['Firebase Firestore', 'Firebase Realtime Database', 'Cloud Firestore'], category: 'tool' },
    { id: 'supabase', name: 'Supabase', variants: [], category: 'tool' },

    // ─── DATA ENGINEERING & STREAMING ────────────────────────────────────────
    { id: 'kafka', name: 'Apache Kafka', variants: ['Kafka', 'Kafka Streams', 'Event Streaming', 'Message Queue', 'Message Broker'], category: 'tool' },
    { id: 'spark', name: 'Apache Spark', variants: ['Spark', 'PySpark', 'Spark SQL'], category: 'tool' },
    { id: 'airflow', name: 'Apache Airflow', variants: ['Airflow', 'Workflow Orchestration', 'Data Pipelines'], category: 'tool' },
    { id: 'dbt', name: 'dbt', variants: ['Data Build Tool', 'dbt Core', 'dbt Cloud'], category: 'tool' },
    { id: 'flink', name: 'Apache Flink', variants: ['Flink', 'Stream Processing'], category: 'tool' },
    { id: 'hadoop', name: 'Hadoop', variants: ['Apache Hadoop', 'HDFS', 'Hive', 'HBase', 'MapReduce'], category: 'tool' },
    { id: 'etl', name: 'ETL', variants: ['Extract Transform Load', 'ELT', 'Data Ingestion', 'Data Integration', 'Data Pipelines'], category: 'hard' },
    { id: 'data_warehousing', name: 'Data Warehousing', variants: ['Data Warehouse', 'DWH', 'OLAP', 'Data Lake', 'Data Lakehouse', 'Data Architecture'], category: 'hard' },
    { id: 'fivetran', name: 'Fivetran', variants: [], category: 'tool' },
    { id: 'talend', name: 'Talend', variants: ['Talend Studio'], category: 'tool' },

    // ─── ML / AI / DATA SCIENCE ───────────────────────────────────────────────
    { id: 'machine_learning', name: 'Machine Learning', variants: ['ML', 'Supervised Learning', 'Unsupervised Learning', 'Reinforcement Learning', 'Model Training', 'Model Deployment', 'Predictive Modeling'], category: 'hard' },
    { id: 'deep_learning', name: 'Deep Learning', variants: ['DL', 'Neural Networks', 'Artificial Neural Networks', 'ANN', 'CNN', 'RNN', 'LSTM', 'Transformer', 'Attention Mechanism'], category: 'hard' },
    { id: 'nlp', name: 'NLP', variants: ['Natural Language Processing', 'Text Mining', 'Sentiment Analysis', 'Named Entity Recognition', 'NER', 'Large Language Models', 'LLM', 'LLMs', 'Text Classification'], category: 'hard' },
    { id: 'computer_vision', name: 'Computer Vision', variants: ['CV', 'Image Recognition', 'Object Detection', 'Image Segmentation', 'OCR'], category: 'hard' },
    { id: 'tensorflow', name: 'TensorFlow', variants: ['TF', 'Keras', 'TensorFlow 2'], category: 'tool' },
    { id: 'pytorch', name: 'PyTorch', variants: ['Torch', 'PyTorch Lightning', 'TorchVision'], category: 'tool' },
    { id: 'scikit_learn', name: 'scikit-learn', variants: ['sklearn', 'Scikit Learn', 'scikit learn'], category: 'tool' },
    { id: 'pandas', name: 'Pandas', variants: ['Pandas DataFrame'], category: 'tool' },
    { id: 'numpy', name: 'NumPy', variants: ['Numpy', 'Numerical Python'], category: 'tool' },
    { id: 'huggingface', name: 'Hugging Face', variants: ['HuggingFace', 'Transformers Library', 'HF Transformers'], category: 'tool' },
    { id: 'langchain', name: 'LangChain', variants: ['Lang Chain'], category: 'tool' },
    { id: 'openai_api', name: 'OpenAI API', variants: ['ChatGPT API', 'GPT-4', 'GPT4', 'GPT-3', 'Generative AI', 'GenAI', 'LLM Integration', 'AI Integration'], category: 'tool' },
    { id: 'mlflow', name: 'MLflow', variants: ['ML Flow', 'Model Registry', 'ML Experiment Tracking'], category: 'tool' },
    { id: 'feature_engineering', name: 'Feature Engineering', variants: ['Feature Selection', 'Feature Extraction', 'Data Preprocessing', 'Data Wrangling'], category: 'hard' },
    { id: 'data_science', name: 'Data Science', variants: ['Data Scientist', 'Statistical Analysis', 'Statistical Modeling', 'Quantitative Analysis'], category: 'hard' },
    { id: 'data_analysis', name: 'Data Analysis', variants: ['Data Analytics', 'Business Analytics', 'Data-Driven Decision Making', 'Descriptive Analytics'], category: 'hard' },
    { id: 'statistics', name: 'Statistics', variants: ['Statistical Inference', 'Hypothesis Testing', 'Regression Analysis', 'Time Series Analysis', 'Bayesian Statistics'], category: 'hard' },
    { id: 'xgboost', name: 'XGBoost', variants: ['LightGBM', 'CatBoost', 'Gradient Boosting'], category: 'tool' },
    { id: 'rag', name: 'RAG', variants: ['Retrieval Augmented Generation', 'Vector Database', 'Pinecone', 'Weaviate', 'Chroma', 'FAISS', 'Embeddings', 'Embedding Model'], category: 'hard' },
    { id: 'ab_testing_data', name: 'A/B Testing', variants: ['Experimentation', 'Statistical Testing', 'Causal Inference'], category: 'hard' },

    // ─── ANALYTICS & BI ───────────────────────────────────────────────────────
    { id: 'tableau', name: 'Tableau', variants: ['Tableau Desktop', 'Tableau Server', 'Tableau Public', 'Tableau Online'], category: 'tool' },
    { id: 'power_bi', name: 'Power BI', variants: ['PowerBI', 'Microsoft Power BI', 'Power BI Desktop', 'DAX', 'Power Query'], category: 'tool' },
    { id: 'looker', name: 'Looker', variants: ['Looker Studio', 'LookML', 'Google Looker'], category: 'tool' },
    { id: 'google_analytics', name: 'Google Analytics', variants: ['GA', 'GA4', 'Google Analytics 4', 'Universal Analytics'], category: 'tool' },
    { id: 'mixpanel', name: 'Mixpanel', variants: ['Mixpanel Analytics'], category: 'tool' },
    { id: 'amplitude', name: 'Amplitude', variants: ['Amplitude Analytics'], category: 'tool' },
    { id: 'excel', name: 'Excel', variants: ['Microsoft Excel', 'MS Excel', 'Spreadsheets', 'VLOOKUP', 'Pivot Tables', 'Excel Macros', 'Excel VBA', 'Advanced Excel'], category: 'tool' },
    { id: 'google_sheets', name: 'Google Sheets', variants: ['G-Sheets', 'Google Spreadsheets', 'GSheets'], category: 'tool' },
    { id: 'metabase', name: 'Metabase', variants: [], category: 'tool' },
    { id: 'qlik', name: 'Qlik', variants: ['Qlik Sense', 'QlikView'], category: 'tool' },
    { id: 'data_visualization', name: 'Data Visualization', variants: ['Data Viz', 'Dashboards', 'Reporting', 'Business Intelligence', 'BI'], category: 'hard' },

    // ─── PROJECT MANAGEMENT ───────────────────────────────────────────────────
    { id: 'jira', name: 'Jira', variants: ['Atlassian Jira', 'Jira Software', 'Jira Service Management'], category: 'tool' },
    { id: 'confluence', name: 'Confluence', variants: ['Atlassian Confluence', 'Confluence Wiki'], category: 'tool' },
    { id: 'asana', name: 'Asana', variants: [], category: 'tool' },
    { id: 'notion', name: 'Notion', variants: ['Notion Workspace'], category: 'tool' },
    { id: 'trello', name: 'Trello', variants: ['Trello Boards'], category: 'tool' },
    { id: 'monday', name: 'Monday.com', variants: ['Monday'], category: 'tool' },
    { id: 'agile', name: 'Agile', variants: ['Agile Methodology', 'Agile Development', 'Agile Practices', 'Agile Frameworks', 'SAFe'], category: 'hard' },
    { id: 'scrum', name: 'Scrum', variants: ['Scrum Master', 'Sprint Planning', 'Sprint Retrospective', 'Daily Standup', 'Backlog Grooming', 'Sprint Review'], category: 'hard' },
    { id: 'kanban', name: 'Kanban', variants: ['Kanban Board', 'Kanban Methodology'], category: 'hard' },
    { id: 'product_management', name: 'Product Management', variants: ['Product Manager', 'Product Strategy', 'Roadmapping', 'Product Roadmap', 'PRD', 'Product Requirements Document'], category: 'hard' },
    { id: 'project_management', name: 'Project Management', variants: ['PMP', 'Project Planning', 'Project Delivery', 'Program Management', 'Portfolio Management'], category: 'hard' },
    { id: 'okrs', name: 'OKRs', variants: ['Objectives and Key Results', 'OKR Framework', 'Goal Setting', 'KPIs', 'Key Performance Indicators'], category: 'hard' },

    // ─── CYBERSECURITY ────────────────────────────────────────────────────────
    { id: 'cybersecurity', name: 'Cybersecurity', variants: ['Information Security', 'InfoSec', 'IT Security', 'Security Engineering', 'Cyber Security'], category: 'hard' },
    { id: 'penetration_testing', name: 'Penetration Testing', variants: ['Pen Testing', 'Pentesting', 'Ethical Hacking', 'Red Team', 'Vulnerability Assessment', 'Vulnerability Management'], category: 'hard' },
    { id: 'soc2', name: 'SOC 2', variants: ['SOC2', 'SOC 2 Type II', 'SOC Compliance'], category: 'certification' },
    { id: 'gdpr', name: 'GDPR', variants: ['General Data Protection Regulation', 'Data Privacy', 'CCPA', 'Privacy Compliance'], category: 'certification' },
    { id: 'iso27001', name: 'ISO 27001', variants: ['ISO 27001', 'Information Security Management', 'ISMS'], category: 'certification' },
    { id: 'owasp', name: 'OWASP', variants: ['OWASP Top 10', 'Web Application Security', 'AppSec'], category: 'hard' },
    { id: 'siem', name: 'SIEM', variants: ['Security Information and Event Management', 'Splunk', 'Sentinel', 'QRadar'], category: 'tool' },
    { id: 'iam', name: 'IAM', variants: ['Identity and Access Management', 'OAuth', 'SAML', 'SSO', 'Single Sign-On', 'OpenID Connect', 'OIDC', 'Active Directory', 'LDAP'], category: 'hard' },
    { id: 'encryption', name: 'Encryption', variants: ['Data Encryption', 'TLS', 'SSL', 'PKI', 'Cryptography'], category: 'hard' },
    { id: 'devsecops', name: 'DevSecOps', variants: ['Security as Code', 'Shift Left Security', 'Secure SDLC'], category: 'hard' },
    { id: 'hipaa', name: 'HIPAA', variants: ['HIPAA Compliance', 'Health Insurance Portability and Accountability Act'], category: 'certification' },
    { id: 'pci_dss', name: 'PCI DSS', variants: ['PCI Compliance', 'Payment Card Industry'], category: 'certification' },
    { id: 'sox', name: 'SOX', variants: ['Sarbanes-Oxley', 'SOX Compliance', 'SOX Controls'], category: 'certification' },

    // ─── CRM & BUSINESS TOOLS ─────────────────────────────────────────────────
    { id: 'salesforce', name: 'Salesforce', variants: ['SFDC', 'Salesforce CRM', 'Salesforce Sales Cloud', 'Salesforce Service Cloud', 'Salesforce Marketing Cloud', 'Apex', 'SOQL', 'Lightning', 'Salesforce Admin'], category: 'tool' },
    { id: 'hubspot', name: 'HubSpot', variants: ['HubSpot CRM', 'HubSpot Marketing', 'HubSpot Sales'], category: 'tool' },
    { id: 'zendesk', name: 'Zendesk', variants: ['Zendesk Support'], category: 'tool' },
    { id: 'sap', name: 'SAP', variants: ['SAP ERP', 'SAP S/4HANA', 'SAP HANA', 'SAP BI', 'SAP Fiori', 'SAP BW'], category: 'tool' },
    { id: 'oracle_apps', name: 'Oracle ERP', variants: ['Oracle Financials', 'Oracle Cloud', 'Oracle NetSuite', 'NetSuite', 'Oracle EBS'], category: 'tool' },
    { id: 'workday', name: 'Workday', variants: ['Workday HCM', 'Workday Finance'], category: 'tool' },
    { id: 'servicenow', name: 'ServiceNow', variants: ['SNOW', 'ServiceNow ITSM'], category: 'tool' },
    { id: 'intercom', name: 'Intercom', variants: [], category: 'tool' },
    { id: 'freshdesk', name: 'Freshdesk', variants: ['Freshworks', 'Freshservice'], category: 'tool' },

    // ─── DESIGN ───────────────────────────────────────────────────────────────
    { id: 'figma', name: 'Figma', variants: ['Figma Design', 'Figma Prototyping', 'FigJam'], category: 'tool' },
    { id: 'sketch', name: 'Sketch', variants: ['Sketch App', 'Sketch Design'], category: 'tool' },
    { id: 'adobe_xd', name: 'Adobe XD', variants: ['AdobeXD', 'XD'], category: 'tool' },
    { id: 'photoshop', name: 'Adobe Photoshop', variants: ['Photoshop', 'PS'], category: 'tool' },
    { id: 'illustrator', name: 'Adobe Illustrator', variants: ['Illustrator', 'AI vector'], category: 'tool' },
    { id: 'invision', name: 'InVision', variants: ['InVision Studio'], category: 'tool' },
    { id: 'ux_design', name: 'UX Design', variants: ['User Experience Design', 'UX Research', 'User Research', 'Usability Testing', 'UX/UI', 'Human-Centered Design', 'Design Thinking', 'Information Architecture'], category: 'hard' },
    { id: 'ui_design', name: 'UI Design', variants: ['User Interface Design', 'UI/UX', 'Interaction Design', 'Visual Design', 'Interface Design'], category: 'hard' },
    { id: 'product_design', name: 'Product Design', variants: ['End-to-End Design', 'Design Systems', 'Wireframing', 'Prototyping', 'Mockups', 'Design System'], category: 'hard' },

    // ─── MARKETING ────────────────────────────────────────────────────────────
    { id: 'seo', name: 'SEO', variants: ['Search Engine Optimization', 'Organic Search', 'Technical SEO', 'On-Page SEO', 'Off-Page SEO', 'Link Building', 'Keyword Research'], category: 'hard' },
    { id: 'sem', name: 'SEM', variants: ['Search Engine Marketing', 'Paid Search', 'PPC', 'Pay-Per-Click', 'Google Ads', 'Google AdWords'], category: 'hard' },
    { id: 'content_marketing', name: 'Content Marketing', variants: ['Content Strategy', 'Content Creation', 'Copywriting', 'Blog Writing'], category: 'hard' },
    { id: 'social_media', name: 'Social Media Marketing', variants: ['Social Media Management', 'Social Media Strategy', 'SMM', 'Facebook Ads', 'Meta Ads', 'Instagram Marketing', 'LinkedIn Marketing', 'TikTok Marketing'], category: 'hard' },
    { id: 'email_marketing', name: 'Email Marketing', variants: ['Email Campaigns', 'Email Automation', 'Mailchimp', 'Klaviyo', 'SendGrid', 'Drip Campaigns', 'Marketo'], category: 'hard' },
    { id: 'marketing_automation', name: 'Marketing Automation', variants: ['Automation Marketing', 'Lead Nurturing', 'Pardot', 'Eloqua'], category: 'hard' },
    { id: 'ab_testing', name: 'A/B Testing', variants: ['Split Testing', 'Multivariate Testing', 'CRO', 'Conversion Rate Optimization'], category: 'hard' },
    { id: 'growth_marketing', name: 'Growth Marketing', variants: ['Growth Hacking', 'Growth Strategy', 'User Acquisition', 'Customer Acquisition', 'Demand Generation', 'PLG', 'Product-Led Growth'], category: 'hard' },
    { id: 'brand_management', name: 'Brand Management', variants: ['Brand Strategy', 'Brand Identity', 'Brand Development', 'Branding'], category: 'hard' },
    { id: 'performance_marketing', name: 'Performance Marketing', variants: ['Paid Media', 'Paid Social', 'Digital Advertising', 'Media Buying', 'Programmatic Advertising', 'Programmatic'], category: 'hard' },
    { id: 'marketing', name: 'Marketing', variants: ['Digital Marketing', 'Integrated Marketing', 'Marketing Strategy', 'Campaign Management', 'Go-to-Market', 'GTM Strategy'], category: 'hard' },

    // ─── FINANCE & ACCOUNTING ─────────────────────────────────────────────────
    { id: 'financial_modeling', name: 'Financial Modeling', variants: ['Financial Model', 'DCF', 'Discounted Cash Flow', 'LBO Model', 'M&A Modeling', 'Three-Statement Model', 'Valuation Modeling', 'Excel Financial Modeling'], category: 'hard' },
    { id: 'financial_analysis', name: 'Financial Analysis', variants: ['Financial Reporting', 'Financial Planning', 'FP&A', 'Financial Planning and Analysis', 'Variance Analysis', 'Budget vs Actual', 'P&L Management'], category: 'hard' },
    { id: 'accounting', name: 'Accounting', variants: ['General Ledger', 'GL', 'Bookkeeping', 'Accounts Payable', 'Accounts Receivable', 'AR/AP', 'Journal Entries', 'Month-End Close', 'Year-End Close'], category: 'hard' },
    { id: 'gaap', name: 'GAAP', variants: ['Generally Accepted Accounting Principles', 'US GAAP'], category: 'certification' },
    { id: 'ifrs', name: 'IFRS', variants: ['International Financial Reporting Standards'], category: 'certification' },
    { id: 'quickbooks', name: 'QuickBooks', variants: ['QuickBooks Online', 'QuickBooks Desktop', 'QBO'], category: 'tool' },
    { id: 'netsuite', name: 'NetSuite', variants: ['Oracle NetSuite'], category: 'tool' },
    { id: 'bloomberg', name: 'Bloomberg', variants: ['Bloomberg Terminal', 'Bloomberg Analytics'], category: 'tool' },
    { id: 'budgeting', name: 'Budgeting', variants: ['Budget Management', 'Budget Planning', 'Forecasting', 'Revenue Forecasting', 'Cost Forecasting', 'Financial Forecasting', 'Annual Planning'], category: 'hard' },
    { id: 'investment_analysis', name: 'Investment Analysis', variants: ['Portfolio Management', 'Asset Management', 'Equity Research', 'Fixed Income', 'Derivatives', 'Risk Management', 'Investment Banking'], category: 'hard' },
    { id: 'audit', name: 'Audit', variants: ['Internal Audit', 'External Audit', 'Auditing', 'Audit Management'], category: 'hard' },
    { id: 'tax', name: 'Tax', variants: ['Tax Planning', 'Tax Compliance', 'Corporate Tax', 'Tax Preparation', 'Tax Advisory', 'Transfer Pricing'], category: 'hard' },
    { id: 'venture_capital', name: 'Venture Capital', variants: ['VC', 'Private Equity', 'PE', 'Investment Banking', 'IB', 'Fundraising', 'Series A', 'Series B', 'Cap Table', 'Term Sheet'], category: 'hard' },
    { id: 'finance', name: 'Finance', variants: ['Corporate Finance', 'Business Finance', 'Financial Management'], category: 'hard' },

    // ─── SALES & BUSINESS DEVELOPMENT ────────────────────────────────────────
    { id: 'sales', name: 'Sales', variants: ['Business Development', 'BD', 'Account Executive', 'AE', 'Sales Development', 'SDR', 'BDR', 'Inside Sales', 'Outside Sales', 'Field Sales', 'Cold Calling', 'Cold Outreach'], category: 'hard' },
    { id: 'account_management', name: 'Account Management', variants: ['Key Account Management', 'KAM', 'Client Management', 'Customer Success', 'CSM', 'Renewals', 'Customer Retention'], category: 'hard' },
    { id: 'b2b_sales', name: 'B2B Sales', variants: ['Enterprise Sales', 'SaaS Sales', 'Solution Selling', 'Consultative Selling', 'MEDDIC', 'SPIN Selling', 'Challenger Sale'], category: 'hard' },
    { id: 'negotiations', name: 'Negotiations', variants: ['Contract Negotiation', 'Deal Negotiation', 'Pricing Negotiation', 'Commercial Negotiation'], category: 'soft' },
    { id: 'revenue_growth', name: 'Revenue Growth', variants: ['Revenue Generation', 'ARR Growth', 'MRR Growth', 'Pipeline Building', 'Quota Attainment', 'Sales Targets', 'Quota'], category: 'hard' },
    { id: 'partnership', name: 'Partnerships', variants: ['Strategic Partnerships', 'Channel Partnerships', 'Partner Management', 'Alliance Management', 'Business Partnerships'], category: 'hard' },

    // ─── OPERATIONS ───────────────────────────────────────────────────────────
    { id: 'operations_management', name: 'Operations Management', variants: ['Operations', 'Ops', 'Business Operations', 'Operational Excellence', 'Process Management'], category: 'hard' },
    { id: 'supply_chain', name: 'Supply Chain', variants: ['Supply Chain Management', 'SCM', 'Logistics', 'Procurement', 'Vendor Management', 'Sourcing', 'Inventory Management', 'Inventory Control', 'Demand Planning'], category: 'hard' },
    { id: 'process_improvement', name: 'Process Improvement', variants: ['Process Optimization', 'Continuous Improvement', 'Lean', 'Six Sigma', 'Kaizen', 'Lean Six Sigma', 'Black Belt', 'Green Belt', 'Business Process Improvement'], category: 'hard' },
    { id: 'quality_assurance', name: 'Quality Assurance', variants: ['QA', 'Quality Control', 'QC', 'Quality Management', 'ISO 9001', 'TQM'], category: 'hard' },
    { id: 'vendor_management', name: 'Vendor Management', variants: ['Supplier Management', 'Third-Party Management', 'Contract Management', 'SLA Management'], category: 'hard' },

    // ─── HR & PEOPLE OPS ──────────────────────────────────────────────────────
    { id: 'talent_acquisition', name: 'Talent Acquisition', variants: ['Recruiting', 'Recruitment', 'Technical Recruiting', 'Full-Cycle Recruiting', 'Sourcing', 'Talent Sourcing', 'Headhunting'], category: 'hard' },
    { id: 'hr_management', name: 'HR Management', variants: ['Human Resources', 'HR', 'People Operations', 'People Ops', 'HRBP', 'HR Business Partner'], category: 'hard' },
    { id: 'performance_management', name: 'Performance Management', variants: ['Performance Reviews', 'Goal Setting', 'Employee Development', 'Talent Development'], category: 'hard' },
    { id: 'compensation', name: 'Compensation & Benefits', variants: ['Total Rewards', 'Compensation Planning', 'Benefits Administration', 'Payroll', 'Compensation Benchmarking'], category: 'hard' },
    { id: 'dei', name: 'DEI', variants: ['Diversity Equity Inclusion', 'Diversity and Inclusion', 'D&I', 'Belonging', 'DEIB'], category: 'hard' },
    { id: 'employee_engagement', name: 'Employee Engagement', variants: ['Employee Experience', 'Culture Building', 'Team Engagement', 'Retention', 'Employee Satisfaction'], category: 'hard' },

    // ─── SOFT SKILLS ──────────────────────────────────────────────────────────
    { id: 'leadership', name: 'Leadership', variants: ['Team Lead', 'Team Leadership', 'People Manager', 'Engineering Manager', 'Technical Lead', 'Tech Lead', 'Spearheaded', 'Orchestrated', 'Directed', 'Led', 'Managed Team'], category: 'soft' },
    { id: 'communication', name: 'Communication', variants: ['Public Speaking', 'Presentation Skills', 'Written Communication', 'Executive Communication', 'Stakeholder Communication', 'Verbal Communication'], category: 'soft' },
    { id: 'stakeholder_management', name: 'Stakeholder Management', variants: ['Executive Stakeholders', 'Cross-functional Stakeholders', 'C-Suite Communication', 'Board Presentation', 'Stakeholder Alignment'], category: 'soft' },
    { id: 'problem_solving', name: 'Problem Solving', variants: ['Troubleshooting', 'Debugged', 'Resolved', 'Analytical Skills', 'Critical Thinking', 'Root Cause Analysis', 'RCA', 'Systems Thinking'], category: 'soft' },
    { id: 'collaboration', name: 'Cross-functional Collaboration', variants: ['Collaboration', 'Team Collaboration', 'Cross-team', 'Interdisciplinary', 'Matrix Organization', 'Cross-functional'], category: 'soft' },
    { id: 'mentoring', name: 'Mentoring', variants: ['Mentorship', 'Coaching', 'Career Development', 'Talent Development', 'Knowledge Transfer', 'Training'], category: 'soft' },
    { id: 'strategic_thinking', name: 'Strategic Planning', variants: ['Strategic Thinking', 'Business Strategy', 'Long-term Planning', 'Vision Setting', 'Strategy Development', 'Corporate Strategy'], category: 'soft' },
    { id: 'innovation', name: 'Innovation', variants: ['Creative Problem Solving', 'Ideation', 'R&D', 'Research and Development', 'Innovation Management'], category: 'soft' },

    // ─── MOBILE DEVELOPMENT ───────────────────────────────────────────────────
    { id: 'react_native', name: 'React Native', variants: ['RN', 'React-Native'], category: 'hard' },
    { id: 'flutter', name: 'Flutter', variants: ['Flutter SDK', 'Flutter Dart'], category: 'hard' },
    { id: 'ios', name: 'iOS Development', variants: ['iOS', 'iPhone', 'iPad', 'Xcode', 'UIKit', 'Objective-C', 'iOS SDK'], category: 'hard' },
    { id: 'android', name: 'Android Development', variants: ['Android', 'Android SDK', 'Android Studio', 'Jetpack Compose', 'Kotlin Android'], category: 'hard' },
    { id: 'mobile_dev', name: 'Mobile Development', variants: ['Mobile App Development', 'Cross-Platform Development', 'PWA', 'Progressive Web App'], category: 'hard' },

    // ─── TESTING & QA ─────────────────────────────────────────────────────────
    { id: 'testing', name: 'Software Testing', variants: ['Unit Testing', 'Integration Testing', 'End-to-End Testing', 'Regression Testing', 'Manual Testing', 'Automated Testing', 'Test Automation', 'TDD', 'Test-Driven Development', 'BDD', 'QA Testing'], category: 'hard' },
    { id: 'selenium', name: 'Selenium', variants: ['Selenium WebDriver', 'Selenium Grid'], category: 'tool' },
    { id: 'postman', name: 'Postman', variants: ['API Testing'], category: 'tool' },

    // ─── PRODUCTIVITY & COMMUNICATION ─────────────────────────────────────────
    { id: 'microsoft_365', name: 'Microsoft 365', variants: ['Office 365', 'Microsoft Office', 'MS Office', 'Word', 'PowerPoint', 'Outlook', 'OneNote', 'SharePoint'], category: 'tool' },
    { id: 'google_workspace', name: 'Google Workspace', variants: ['G Suite', 'Google Docs', 'Google Drive', 'Google Slides', 'Gmail', 'Google Meet'], category: 'tool' },
    { id: 'slack', name: 'Slack', variants: ['Slack Workspace', 'Slack Integration'], category: 'tool' },

    // ─── CERTIFICATIONS ───────────────────────────────────────────────────────
    { id: 'aws_cert', name: 'AWS Certified', variants: ['AWS Solutions Architect', 'AWS Developer Associate', 'AWS DevOps Professional', 'AWS Cloud Practitioner', 'AWS SysOps Administrator'], category: 'certification' },
    { id: 'gcp_cert', name: 'GCP Certified', variants: ['Google Cloud Certified', 'GCP Professional', 'Google Cloud Associate', 'Google Cloud Professional'], category: 'certification' },
    { id: 'azure_cert', name: 'Azure Certified', variants: ['Microsoft Certified Azure', 'AZ-900', 'AZ-104', 'AZ-204', 'AZ-400', 'Azure Administrator', 'Azure Developer'], category: 'certification' },
    { id: 'cpa', name: 'CPA', variants: ['Certified Public Accountant'], category: 'certification' },
    { id: 'cfa', name: 'CFA', variants: ['Chartered Financial Analyst', 'CFA Charter', 'CFA Level'], category: 'certification' },
    { id: 'pmp', name: 'PMP', variants: ['Project Management Professional', 'PMP Certification', 'PMP Certified'], category: 'certification' },
    { id: 'cissp', name: 'CISSP', variants: ['Certified Information Systems Security Professional'], category: 'certification' },
    { id: 'scrum_master', name: 'Certified Scrum Master', variants: ['CSM', 'Professional Scrum Master', 'PSM', 'SAFe Scrum Master', 'Scrum Certification'], category: 'certification' },
];

// Common abbreviations mapped to their canonical skill names
export const ABBREVIATIONS: Record<string, string> = {
    'ml': 'Machine Learning',
    'dl': 'Deep Learning',
    'ai': 'Artificial Intelligence',
    'nlp': 'NLP',
    'cv': 'Computer Vision',
    'k8s': 'Kubernetes',
    'k8': 'Kubernetes',
    'tf': 'TensorFlow',
    'gcp': 'GCP',
    'az': 'Azure',
    'js': 'JavaScript',
    'ts': 'TypeScript',
    'py': 'Python',
    'rb': 'Ruby',
    'ror': 'Ruby on Rails',
    'rn': 'React Native',
    'iac': 'Terraform',
    'etl': 'ETL',
    'elt': 'ETL',
    'bi': 'Power BI',
    'ci/cd': 'CI/CD',
    'cicd': 'CI/CD',
    'sre': 'DevOps',
    'qa': 'Quality Assurance',
    'ux': 'UX Design',
    'ui': 'UI Design',
    'ppc': 'SEM',
    'crm': 'Salesforce',
    'erp': 'SAP',
    'cpa': 'CPA',
    'cfa': 'CFA',
    'pmp': 'PMP',
    'csm': 'Certified Scrum Master',
    'rag': 'RAG',
    'llm': 'NLP',
    'llms': 'NLP',
    'genai': 'OpenAI API',
    'gen ai': 'OpenAI API',
    'bd': 'Sales',
    'bdr': 'Sales',
    'sdr': 'Sales',
    'dei': 'DEI',
    'hr': 'HR Management',
    'fp&a': 'Financial Analysis',
    'fpa': 'Financial Analysis',
    'dcf': 'Financial Modeling',
    'vc': 'Venture Capital',
    'pe': 'Venture Capital',
    'ib': 'Venture Capital',
    'm&a': 'Financial Modeling',
    'scm': 'Supply Chain',
    'okr': 'OKRs',
    'okrs': 'OKRs',
    'devops': 'DevOps',
    'devsecops': 'DevSecOps',
    'kpi': 'OKRs',
    'kpis': 'OKRs',
    'plg': 'Growth Marketing',
    'gtm': 'Marketing',
};

export const normalizeSkill = (text: string): string | null => {
    const lower = text.toLowerCase().trim();
    if (ABBREVIATIONS[lower]) return ABBREVIATIONS[lower];
    for (const skill of SKILL_DATABASE) {
        if (skill.name.toLowerCase() === lower) return skill.name;
        if (skill.variants.some(v => v.toLowerCase() === lower)) return skill.name;
    }
    return null;
};
